//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMyRoom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int RoomId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public Nullable<bool> Reccursive { get; set; }
        public string ReccursiveType { get; set; }
        public Nullable<int> ReccursiveValue { get; set; }
        public string Attendees { get; set; }
        public string BookedBy { get; set; }
        public string BookedFor { get; set; }
        public byte[] BookedOn { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
